//Tabs
export const UPDATE_TAB_SUCCESS = 'UPDATE_TAB_SUCCESS';
export const CREATE_TAB_SUCCESS = 'CREATE_TAB_SUCCESS';
export const CLEAR_TABS = 'CLEAR_TABS';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB';

//App
export const ON_LOADING = 'ON_LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';